remote_theme: pages-themes/cayman@v0.2.0
plugins: 
- jekyll-remote-theme
title: CostTracker
description: CostTracker merupakan sebuah aplikasi desktop yang dapat mencatat seluruh pengeluaran dan pemasukan yang dilakukan untuk membantu mengatur keuangan penggunanya.
